### ISSUE TITLE
NAT超えする場合としない場合のスクリプトの使い分けについて説明する

### ISSUE THREAD

**Issue by MikhailBertrand** [sbgisen/kachaka-api-for-openrmf#6]
**概要**

README内で2つのスクリプトの使い分け・使い道について説明する。

- rest_kachaka_api.py
  - **NAT越えをしない**場合（同一ネットワーク内に存在するOpen-RMFサーバーとのトピックの送受信を実施する場合）に用いる
  - [fleet_adapter_kachaka](https://github.com/sbgisen/fleet_adapter_kachaka)をフリートアダプタとして用いる
  - fleet adapterでほしいトピックが取れるようにするためにFastAPIを利用する

- connect_openrmf_by_zenoh.py
  - **NAT越えをする**場合（AWSインスタンス上に設置したOpen-RMFサーバーとのトピックの送受信を実施する場合）に用いる
  - AWS上に設置したZenohトピックを送受信する共通アダプタをフリートアダプタとして用いる
  - 通信の効率化のためにZenohを利用する

**Comment by h-wata** [comment]
そうですね。あっています。

**Comment by MikhailBertrand** [comment]
#7 で追加したconfigファイルの使い方も記載の必要あり
